### ISSUE TITLE
Prettify readme presentation

### ISSUE THREAD

**Issue by anshumanv** [cerebro-iiitv/cerebro-web#39]
Add details about the tech stack used, what this app is for, about cerebro, add screenshots of pages and how this app works, any other details that feel suitable.

**Comment by anshumanv** [comment]
@Lucifer24 up for this?

**Comment by aashutoshrathi** [comment]
Anyone up for this?
Should we complete it after we are done with fixing stuff?

**Comment by aashutoshrathi** [comment]
Taking it @anshumanv

**Comment by Monal5031** [comment]
Ping @aashutoshrathi
